//! The control-plane HTTP API ([[WEIR-S-0002]] / [[WEIR-A-0006]]) — an `axum`
//! router over [`weir_app::App`], plus the embedded Leptos UI. [`router`] is a
//! plain function, testable via `oneshot` without binding a port.

use std::sync::Arc;
use std::time::{Duration, Instant};

use axum::{
    Json, Router,
    extract::{Path, Request, State},
    http::{StatusCode, Uri, header},
    middleware::Next,
    response::{IntoResponse, Response},
    routing::{delete, get, post},
};
use lru::LruCache;
use serde::{Deserialize, Serialize};
use tokio::sync::Mutex;

use weir_app::{
    App, AppError, AuthenticatedKey, CatalogEntry, Connection, ConnectionState, ConnectorSpec,
    DeadLetterRecord, LogRecord, Origin, RunRow, Source, WorkUnitStatus, connector_ref,
    plugin_name,
};

mod authz;
mod oidc;

// Prometheus metrics ([[WEIR-T-0099]]): install the global recorder once; `/metrics` renders the text.
static METRICS_HANDLE: std::sync::OnceLock<metrics_exporter_prometheus::PrometheusHandle> =
    std::sync::OnceLock::new();

fn metrics_handle() -> &'static metrics_exporter_prometheus::PrometheusHandle {
    METRICS_HANDLE.get_or_init(|| {
        metrics_exporter_prometheus::PrometheusBuilder::new()
            .install_recorder()
            .expect("install prometheus recorder")
    })
}

/// `GET /metrics` — public (like `/health`), Prometheus text format. The run path emits to the global
/// recorder ([[WEIR-T-0099]]); aggregate labels by default (no tenant leak).
async fn metrics_handler() -> Response {
    (
        [(header::CONTENT_TYPE, "text/plain; version=0.0.4")],
        metrics_handle().render(),
    )
        .into_response()
}

// Embedded Leptos UI assets (generated by build.rs; empty until `trunk build`
// is run in `weir-ui/`, in which case a placeholder page is served).
include!(concat!(env!("OUT_DIR"), "/ui_assets.rs"));

/// JSON view of a connection (source/dest as plugin names, config as raw JSON).
#[derive(Debug, Serialize, Deserialize)]
pub struct ConnectionDto {
    pub name: String,
    pub source: String,
    pub dest: String,
    pub stream: String,
    // `config` is the both-sides convenience ([[WEIR-I-0029]]); `source_config`/`dest_config` override
    // each side when present.
    #[serde(default = "empty_obj")]
    pub config: serde_json::Value,
    #[serde(default)]
    pub source_config: Option<serde_json::Value>,
    #[serde(default)]
    pub dest_config: Option<serde_json::Value>,
    #[serde(default)]
    pub every_secs: Option<f64>,
    #[serde(default)]
    pub cron: Option<String>,
    // Per-connection sync/write modes ([[WEIR-I-0028]]); defaults reproduce full-refresh + append.
    #[serde(default = "full_refresh")]
    pub sync_mode: String,
    #[serde(default = "append")]
    pub write_mode: String,
    #[serde(default)]
    pub business_keys: Vec<String>,
    #[serde(default)]
    pub cursor_field: Option<String>,
    // Execution mode ([[WEIR-I-0035]] F1): `run_once` (default) | `resident`.
    #[serde(default = "run_once")]
    pub execution_mode: String,
    // Read-only committed state (populated on list; ignored on create).
    #[serde(default)]
    pub cursor: Option<String>,
    #[serde(default)]
    pub chunks: i64,
    #[serde(default)]
    pub dead_lettered: i64,
}

fn empty_obj() -> serde_json::Value {
    serde_json::json!({})
}
fn full_refresh() -> String {
    "full_refresh".to_string()
}
fn append() -> String {
    "append".to_string()
}
fn run_once() -> String {
    "run_once".to_string()
}

impl ConnectionDto {
    fn into_connection(self) -> Connection {
        Connection {
            name: self.name,
            source: connector_ref(&self.source),
            dest: connector_ref(&self.dest),
            stream: self.stream,
            // Per-side config: the explicit override wins, else the `config` convenience for both.
            source_config: self
                .source_config
                .unwrap_or_else(|| self.config.clone())
                .to_string(),
            dest_config: self.dest_config.unwrap_or(self.config).to_string(),
            every_secs: self.every_secs,
            cron: self.cron,
            sync_mode: self.sync_mode,
            write_mode: self.write_mode,
            business_keys: self.business_keys,
            cursor_field: self.cursor_field,
            execution_mode: self.execution_mode,
        }
    }

    fn from_connection(c: &Connection) -> Self {
        Self {
            name: c.name.clone(),
            source: plugin_name(&c.source),
            dest: plugin_name(&c.dest),
            stream: c.stream.clone(),
            config: empty_obj(), // write-only convenience; the per-side configs carry the truth
            source_config: Some(
                serde_json::from_str(&c.source_config).unwrap_or_else(|_| empty_obj()),
            ),
            dest_config: Some(serde_json::from_str(&c.dest_config).unwrap_or_else(|_| empty_obj())),
            every_secs: c.every_secs,
            cron: c.cron.clone(),
            sync_mode: c.sync_mode.clone(),
            write_mode: c.write_mode.clone(),
            business_keys: c.business_keys.clone(),
            cursor_field: c.cursor_field.clone(),
            execution_mode: c.execution_mode.clone(),
            cursor: None,
            chunks: 0,
            dead_lettered: 0,
        }
    }
}

#[derive(Debug, Serialize)]
pub struct RunDto {
    pub work_unit_id: i64,
    pub state: String,
}

/// Build the control-plane router over a shared [`App`]. The API routes require a valid
/// `Authorization: Bearer <api-key>` ([[WEIR-A-0008]] / [[WEIR-T-0084]], mirroring cloacina);
/// `/health` + the SPA fallback are registered outside the auth layer and stay public.
pub fn router(app: Arc<App>) -> Router {
    // Install the Prometheus recorder before the worker emits ([[WEIR-T-0099]]).
    let _ = metrics_handle();
    let auth = AuthState {
        app: Arc::clone(&app),
        cache: Arc::new(KeyCache::new(256, Duration::from_secs(30))),
    };
    let api = Router::new()
        .route("/connections", get(list).post(create))
        .route("/connections/{name}", get(fetch).delete(remove))
        .route("/connections/{name}/run", post(run))
        .route("/connections/{name}/start", post(start))
        .route("/connections/{name}/stop", post(stop))
        .route("/connections/{name}/runs", get(runs))
        .route("/connections/{name}/dead-letters", get(dead_letters))
        .route("/connections/{name}/logs", get(logs))
        .route("/connections/{name}/state", get(state))
        // Typed schema + drift ([[WEIR-T-0121]] / [[WEIR-I-0025]]).
        .route("/connections/{name}/schema", get(schema_view))
        .route("/connections/{name}/schema/accept", post(schema_accept))
        .route("/connectors/{plugin}/spec", get(connector_spec))
        .route("/connectors/{plugin}/discover", post(connector_discover))
        // Connector catalog ([[WEIR-I-0010]] S3): registered list, folder-scan
        // availability, import (ingress), unregister.
        .route("/catalog", get(catalog_list))
        .route("/catalog/available", get(catalog_available))
        .route("/catalog/import", post(catalog_import))
        .route("/catalog/preview", post(catalog_preview))
        .route("/catalog/{name}/{version}", delete(catalog_unregister))
        .route("/runs", get(recent))
        // Holistic ops health ([[WEIR-T-0110]] / [[WEIR-I-0024]]) — implicit-tenant per-connection health.
        .route("/overview", get(overview))
        // Tenant administration (platform-admin only — [[WEIR-T-0090]]).
        .route("/tenants", get(tenants_list).post(tenants_create))
        .route("/tenants/{id}", delete(tenants_delete))
        .route("/tenants/{id}/keys", get(tenant_keys_list).post(tenant_keys_create))
        .route("/tenants/{id}/keys/{kid}", delete(tenant_keys_revoke))
        // Admin cross-tenant data browse ([[WEIR-T-0094]]) — the switcher's target.
        .route("/tenants/{id}/connections", get(t_connections))
        .route("/tenants/{id}/connections/{name}", get(t_connection))
        .route("/tenants/{id}/connections/{name}/run", post(t_run))
        .route("/tenants/{id}/connections/{name}/start", post(t_start))
        .route("/tenants/{id}/connections/{name}/stop", post(t_stop))
        .route("/tenants/{id}/connections/{name}/runs", get(t_runs))
        .route("/tenants/{id}/connections/{name}/dead-letters", get(t_dead_letters))
        .route("/tenants/{id}/connections/{name}/logs", get(t_logs))
        .route("/tenants/{id}/connections/{name}/state", get(t_state))
        .route("/tenants/{id}/catalog", get(t_catalog))
        .route("/tenants/{id}/runs", get(t_recent))
        // Explicit-tenant health (admin cross-tenant) + the platform-wide rollup ([[WEIR-T-0110]]).
        .route("/tenants/{id}/overview", get(t_overview))
        .route("/platform/health", get(platform_overview))
        .route("/auth/me", get(auth_me))
        // Layers run outermost-first: AuthN resolves the key, then AuthZ + audit gate the route.
        .route_layer(axum::middleware::from_fn_with_state(Arc::clone(&app), authz::authz_mw))
        .route_layer(axum::middleware::from_fn_with_state(auth, require_auth));
    // Public OIDC routes carry their own state (config + in-flight login store + lazily-discovered
    // provider); the SPA fallback + /health + /auth/logout are public too.
    let oidc_routes = Router::new()
        .route("/auth/login", get(oidc::auth_login))
        .route("/auth/callback", get(oidc::auth_callback))
        .with_state(oidc::OidcState::from_env(Arc::clone(&app)));
    Router::new()
        .route("/health", get(|| async { "ok" }))
        .route("/metrics", get(metrics_handler))
        .route("/auth/logout", get(auth_logout))
        .merge(oidc_routes)
        .merge(api)
        .fallback(serve_ui)
        .with_state(app)
        // Outermost: log every request's method + full path + status (`RUST_LOG=weir_api=debug`).
        .layer(axum::middleware::from_fn(log_request))
}

/// Lightweight access log ([[WEIR-I-0035]] F1 diagnostics): method, the FULL path (so
/// tenant-scoped `/tenants/{id}/runs` vs `/runs` is visible), and the response status.
/// Bodies are never logged — this stays cheap on the hot path.
async fn log_request(req: Request, next: Next) -> Response {
    let method = req.method().clone();
    let path = req
        .uri()
        .path_and_query()
        .map(|pq| pq.as_str().to_owned())
        .unwrap_or_else(|| req.uri().path().to_owned());
    let resp = next.run(req).await;
    tracing::debug!(target: "weir_api::http", method = %method, path = %path, status = %resp.status().as_u16(), "http request");
    resp
}

/// A validated key cached with a TTL (cloacina's `KeyCache`, `routes/auth.rs`).
struct CachedKey {
    key: AuthenticatedKey,
    at: Instant,
}

/// LRU cache of validated keys (by SHA-256 hash) with TTL expiry — skips the DB on hot paths.
struct KeyCache {
    cache: Mutex<LruCache<String, CachedKey>>,
    ttl: Duration,
}

impl KeyCache {
    fn new(capacity: usize, ttl: Duration) -> Self {
        Self {
            cache: Mutex::new(LruCache::new(
                std::num::NonZeroUsize::new(capacity).expect("cache capacity > 0"),
            )),
            ttl,
        }
    }

    async fn get(&self, hash: &str) -> Option<AuthenticatedKey> {
        let mut c = self.cache.lock().await;
        if let Some(entry) = c.get(hash) {
            if entry.at.elapsed() < self.ttl {
                return Some(entry.key.clone());
            }
            c.pop(hash);
        }
        None
    }

    async fn insert(&self, hash: String, key: AuthenticatedKey) {
        self.cache.lock().await.put(
            hash,
            CachedKey {
                key,
                at: Instant::now(),
            },
        );
    }
}

#[derive(Clone)]
struct AuthState {
    app: Arc<App>,
    cache: Arc<KeyCache>,
}

/// AuthN layer: require `Authorization: Bearer <api-key>`. Checks the LRU cache, else validates
/// against the store; on success inserts an [`AuthenticatedKey`] extension (for [[WEIR-T-0085]]
/// authz + audit); else 401.
async fn require_auth(State(auth): State<AuthState>, mut req: Request, next: Next) -> Response {
    // Two doors ([[WEIR-A-0008]]): the `Authorization: Bearer` header (machines) or the
    // `weir_session` cookie holding an OIDC-minted key (humans, [[WEIR-T-0086]]).
    let presented = req
        .headers()
        .get(header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok())
        .and_then(|s| s.strip_prefix("Bearer "))
        // An empty bearer (the UI sends one when no key is stored) must fall through to the cookie.
        .filter(|s| !s.is_empty())
        .map(str::to_owned)
        .or_else(|| session_cookie(req.headers()));
    let Some(key) = presented else {
        return unauthorized();
    };
    let hash = weir_app::auth::hash_api_key(&key);
    let authed = match auth.cache.get(&hash).await {
        Some(k) => Some(k),
        None => match auth.app.validate_api_key(&key) {
            Ok(Some(k)) => {
                auth.cache.insert(hash, k.clone()).await;
                Some(k)
            }
            _ => None,
        },
    };
    match authed {
        Some(k) => {
            req.extensions_mut().insert(k);
            next.run(req).await
        }
        None => unauthorized(),
    }
}

fn unauthorized() -> Response {
    (
        StatusCode::UNAUTHORIZED,
        Json(serde_json::json!({
            "error": "unauthorized: present a valid `Authorization: Bearer <api-key>`"
        })),
    )
        .into_response()
}

/// Read the `weir_session` cookie ([[WEIR-T-0086]], the human 2nd door — it holds an OIDC-minted key).
fn session_cookie(headers: &axum::http::HeaderMap) -> Option<String> {
    headers
        .get(header::COOKIE)?
        .to_str()
        .ok()?
        .split(';')
        .filter_map(|kv| kv.trim().split_once('='))
        .find(|(k, _)| *k == "weir_session")
        .map(|(_, v)| v.to_string())
}

/// `GET /auth/me` — the current principal, for the UI sign-in gate ([[WEIR-T-0087]]). Authenticated.
async fn auth_me(
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
) -> Json<serde_json::Value> {
    Json(serde_json::json!({
        "subject": format!("key:{}", key.name),
        "name": key.name,
        "role": key.permissions,
        "tenant": key.tenant_id,
        "is_admin": key.is_admin,
    }))
}

/// `GET /auth/logout` — clear the session cookie. Public (works even with an expired session).
async fn auth_logout() -> Response {
    (
        [(
            header::SET_COOKIE,
            "weir_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0",
        )],
        Json(serde_json::json!({ "ok": true })),
    )
        .into_response()
}

const FALLBACK_HTML: &str = "<!doctype html><html><head><meta charset=\"utf-8\"><title>weir</title></head>\
<body style=\"font-family:system-ui;background:#0e1116;color:#e6edf3;padding:40px\">\
<h1>weir</h1><p>The web UI isn't built into this binary. Run <code>trunk build</code> in \
<code>weir-ui/</code> and rebuild.</p></body></html>";

/// Serve the embedded Leptos UI (assets + SPA fallback). Falls back to a small
/// placeholder when the UI hasn't been built into the binary.
async fn serve_ui(uri: Uri) -> Response {
    let path = uri.path().trim_start_matches('/');
    let path = if path.is_empty() { "index.html" } else { path };

    if let Some((_, bytes)) = UI_FILES.iter().find(|(p, _)| *p == path) {
        return ([(header::CONTENT_TYPE, content_type(path))], *bytes).into_response();
    }
    // SPA fallback to index.html if the UI is embedded; else the placeholder.
    if let Some((_, bytes)) = UI_FILES.iter().find(|(p, _)| *p == "index.html") {
        return ([(header::CONTENT_TYPE, "text/html")], *bytes).into_response();
    }
    ([(header::CONTENT_TYPE, "text/html")], FALLBACK_HTML).into_response()
}

fn content_type(path: &str) -> &'static str {
    match path.rsplit('.').next() {
        Some("html") => "text/html",
        Some("js") => "text/javascript",
        Some("wasm") => "application/wasm",
        Some("css") => "text/css",
        Some("json") => "application/json",
        _ => "application/octet-stream",
    }
}

/// Serve the API on `port` until the process exits. Single-node: a background task
/// runs the **scheduler + worker** in-process (`App::serve`, 100 ms poll) so
/// scheduled connections fire (sub-second intervals supported, [[WEIR-T-0051]]),
/// UI add/edit is reconciled live, and triggered runs drain asynchronously — the UI
/// watches them go pending → done/failed in real time.
pub async fn serve(app: Arc<App>, port: u16, concurrency: usize) -> std::io::Result<()> {
    let bg = Arc::clone(&app);
    tokio::spawn(async move {
        let _ = bg
            .serve(
                std::time::Duration::from_millis(100),
                concurrency,
                std::future::pending::<()>(),
            )
            .await;
    });
    let listener = tokio::net::TcpListener::bind(("0.0.0.0", port)).await?;
    axum::serve(listener, router(app)).await
}

/// The caller's tenant, taken implicitly from their key ([[WEIR-A-0036]] decision 3). A global key
/// (no `tenant_id`) acts on the `default` tenant. Handlers scope all data by this.
fn tenant_of(key: &AuthenticatedKey) -> &str {
    key.tenant_id.as_deref().unwrap_or(weir_app::DEFAULT_TENANT)
}

async fn list(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
) -> Result<Json<Vec<ConnectionDto>>, ApiError> {
    let tenant = tenant_of(&key);
    let mut dtos = Vec::new();
    for c in app.list_connections(tenant)? {
        let mut dto = ConnectionDto::from_connection(&c);
        // Enrich with the committed resume point + progress for the card viz.
        if let Ok(st) = app.connection_state(tenant, &c.name) {
            dto.cursor = st.cursor;
            dto.chunks = st.chunks;
            dto.dead_lettered = st.dead_lettered;
        }
        dtos.push(dto);
    }
    Ok(Json(dtos))
}

async fn create(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Json(dto): Json<ConnectionDto>,
) -> Result<StatusCode, ApiError> {
    app.add_connection(tenant_of(&key), &dto.into_connection())?;
    Ok(StatusCode::CREATED)
}

async fn fetch(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Path(name): Path<String>,
) -> Result<Json<ConnectionDto>, ApiError> {
    Ok(Json(ConnectionDto::from_connection(
        &app.get_connection(tenant_of(&key), &name)?,
    )))
}

async fn remove(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Path(name): Path<String>,
) -> Result<StatusCode, ApiError> {
    app.delete_connection(tenant_of(&key), &name)?;
    Ok(StatusCode::NO_CONTENT)
}

async fn run(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Path(name): Path<String>,
) -> Result<Json<RunDto>, ApiError> {
    // Async: enqueue and return immediately; the background worker executes it.
    let id = app.plan_run(tenant_of(&key), &name)?;
    Ok(Json(RunDto {
        work_unit_id: id,
        state: "pending".to_string(),
    }))
}

/// Launch a **resident** connection (enqueue-once). Idempotent: `started=false` if already running.
/// 400 if the connection isn't resident (use `/run` for one-shot), 404 if it doesn't exist.
async fn start(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Path(name): Path<String>,
) -> Result<Json<serde_json::Value>, ApiError> {
    let id = app.start(tenant_of(&key), &name)?;
    Ok(Json(serde_json::json!({
        "name": name, "started": id.is_some(), "work_unit_id": id,
    })))
}

/// Stop a resident connection (durable cancel of its active units). Returns the count cancelled.
async fn stop(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Path(name): Path<String>,
) -> Result<Json<serde_json::Value>, ApiError> {
    let cancelled = app.stop(tenant_of(&key), &name)?;
    Ok(Json(
        serde_json::json!({ "name": name, "cancelled": cancelled }),
    ))
}

async fn runs(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Path(name): Path<String>,
) -> Result<Json<Vec<WorkUnitStatus>>, ApiError> {
    Ok(Json(app.history(tenant_of(&key), &name)?))
}

async fn recent(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
) -> Result<Json<Vec<RunRow>>, ApiError> {
    Ok(Json(app.recent_runs(tenant_of(&key), 50)?))
}

/// Recent dead-lettered records for a connection — the *what + why* behind the count.
async fn dead_letters(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Path(name): Path<String>,
) -> Result<Json<Vec<DeadLetterRecord>>, ApiError> {
    Ok(Json(app.dead_letters(tenant_of(&key), &name, 200)?))
}

/// Recent run logs for a connection (connector logs + write diagnostics).
async fn logs(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Path(name): Path<String>,
) -> Result<Json<Vec<LogRecord>>, ApiError> {
    Ok(Json(app.logs(tenant_of(&key), &name, 200)?))
}

/// A connector's static spec (roles + config_schema) — for the schema-driven config form.
async fn connector_spec(
    State(app): State<Arc<App>>,
    Path(plugin): Path<String>,
) -> Result<Json<ConnectorSpec>, ApiError> {
    Ok(Json(app.connector_spec(&plugin)?))
}

/// Discover a source connector's streams ([[WEIR-T-0050]]) — live, config-dependent.
/// Body is the connector config (JSON object); returns stream names.
async fn connector_discover(
    State(app): State<Arc<App>>,
    Path(plugin): Path<String>,
    body: String,
) -> Result<Json<Vec<String>>, ApiError> {
    let config = if body.trim().is_empty() {
        "{}".to_string()
    } else {
        body
    };
    Ok(Json(app.discover_streams(&plugin, &config)?))
}

/// The registered connector catalog ([[WEIR-I-0010]]) — the caller's tenant only.
async fn catalog_list(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
) -> Result<Json<Vec<CatalogEntry>>, ApiError> {
    Ok(Json(app.list_connectors(tenant_of(&key))?))
}

/// Staged packages available to register (folder scan).
async fn catalog_available(State(app): State<Arc<App>>) -> Json<Vec<weir_app::AvailablePackage>> {
    Json(app.available_packages())
}

/// Import request — exactly one of: `path` (local crate, compiled), `package`
/// (already-staged folder), or `manifest` (declarative yaml, registered instantly).
#[derive(Deserialize)]
struct ImportDto {
    path: Option<String>,
    package: Option<String>,
    manifest: Option<String>,
    /// A vendored manifest selected by name from `/catalog/available` (read + import).
    manifest_name: Option<String>,
    /// A vendored **destination** manifest selected by name ([[WEIR-I-0015]]).
    dest_manifest_name: Option<String>,
    /// Optional name for a `manifest` import (else derived from the manifest).
    name: Option<String>,
}

/// Import (register) a connector via the ingress pipeline; `origin = private`.
async fn catalog_import(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Json(dto): Json<ImportDto>,
) -> Result<Json<CatalogEntry>, ApiError> {
    let tenant = tenant_of(&key);
    // A vendored manifest picked by name (discover & select) → read + onboard.
    if let Some(mname) = dto.manifest_name {
        return Ok(Json(app.import_vendored_manifest(
            tenant,
            &mname,
            Origin::Community,
        )?));
    }
    // A vendored **destination** manifest picked by name → onboard as rest-dest ([[WEIR-I-0015]]).
    if let Some(dname) = dto.dest_manifest_name {
        return Ok(Json(app.import_vendored_dest_manifest(
            tenant,
            &dname,
            Origin::Community,
        )?));
    }
    let source = match (dto.path, dto.package, dto.manifest) {
        (Some(p), _, _) => Source::LocalCrate(p.into()),
        (_, Some(pkg), _) => Source::Folder { package: pkg },
        (_, _, Some(yaml)) => Source::Manifest {
            yaml,
            name: dto.name,
        },
        _ => {
            return Err(ApiError(
                StatusCode::BAD_REQUEST,
                "`path`, `package`, or `manifest` required".into(),
            ));
        }
    };
    Ok(Json(app.import(tenant, source, Origin::Private)?))
}

/// Preview request — a declarative manifest yaml.
#[derive(Deserialize)]
struct PreviewDto {
    manifest: String,
}

/// Dry-run a manifest ([[WEIR-T-0055]]): tier / confidence / streams / unsupported,
/// no compile, no run, no registration.
async fn catalog_preview(
    State(app): State<Arc<App>>,
    Json(dto): Json<PreviewDto>,
) -> Json<weir_app::ImportReport> {
    Json(app.preview_manifest(&dto.manifest))
}

/// Unregister a catalog `(name, version)`.
async fn catalog_unregister(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Path((name, version)): Path<(String, String)>,
) -> Result<StatusCode, ApiError> {
    app.unregister_connector(tenant_of(&key), &name, &version)?;
    Ok(StatusCode::NO_CONTENT)
}

/// Per-connection committed state: resume cursor + chunk/dead-letter counters.
async fn state(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Path(name): Path<String>,
) -> Result<Json<ConnectionState>, ApiError> {
    Ok(Json(app.connection_state(tenant_of(&key), &name)?))
}

/// A connection's captured typed schema + any breaking-drift flag ([[WEIR-T-0121]]).
#[derive(serde::Serialize)]
struct SchemaView {
    fields: Vec<weir_app::Field>,
    /// The breaking-drift reason, if the schema is flagged; `null` when healthy.
    broken: Option<String>,
}

fn schema_of(app: &App, tenant: &str, name: &str) -> Result<SchemaView, ApiError> {
    let conn = app.get_connection(tenant, name)?;
    let fields = app
        .get_stream_schema(tenant, name, &conn.stream)?
        .map(|s| s.fields)
        .unwrap_or_default();
    let broken = app.schema_broken(tenant, name, &conn.stream)?;
    Ok(SchemaView { fields, broken })
}

async fn schema_view(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Path(name): Path<String>,
) -> Result<Json<SchemaView>, ApiError> {
    Ok(Json(schema_of(&app, tenant_of(&key), &name)?))
}

async fn schema_accept(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
    Path(name): Path<String>,
) -> Result<StatusCode, ApiError> {
    let tenant = tenant_of(&key);
    let conn = app.get_connection(tenant, &name)?;
    app.accept_schema(tenant, &name, &conn.stream)?;
    Ok(StatusCode::NO_CONTENT)
}

// ---- Holistic ops health ([[WEIR-T-0110]] / [[WEIR-I-0024]]) ----

fn health_now_ms() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0)
}

/// Per-connection health for the caller's own tenant (implicit-tenant).
async fn overview(
    State(app): State<Arc<App>>,
    axum::Extension(key): axum::Extension<AuthenticatedKey>,
) -> Result<Json<Vec<weir_app::ConnectionHealth>>, ApiError> {
    Ok(Json(app.tenant_health(tenant_of(&key), health_now_ms())?))
}

/// Per-connection health for an explicit tenant (platform-admin cross-tenant browse).
async fn t_overview(
    State(app): State<Arc<App>>,
    Path(id): Path<String>,
) -> Result<Json<Vec<weir_app::ConnectionHealth>>, ApiError> {
    Ok(Json(app.tenant_health(&id, health_now_ms())?))
}

/// The platform-wide health rollup — per-tenant status + cross-tenant "needs attention" + fleet
/// (platform-admin only).
async fn platform_overview(
    State(app): State<Arc<App>>,
) -> Result<Json<weir_app::PlatformHealth>, ApiError> {
    Ok(Json(app.platform_health(health_now_ms())?))
}

// ---- Tenant administration ([[WEIR-T-0090]]) — platform-admin only (authz `Scope::Platform`) ----

#[derive(serde::Serialize)]
struct TenantInfo {
    id: String,
    name: String,
    created_at: i64,
}

impl From<weir_app::Tenant> for TenantInfo {
    fn from(t: weir_app::Tenant) -> Self {
        TenantInfo {
            id: t.id,
            name: t.name,
            created_at: t.created_at,
        }
    }
}

async fn tenants_list(State(app): State<Arc<App>>) -> Result<Json<Vec<TenantInfo>>, ApiError> {
    Ok(Json(
        app.list_tenants()?
            .into_iter()
            .map(TenantInfo::from)
            .collect(),
    ))
}

#[derive(serde::Deserialize)]
struct NewTenantDto {
    id: String,
    name: Option<String>,
}

async fn tenants_create(
    State(app): State<Arc<App>>,
    Json(dto): Json<NewTenantDto>,
) -> Result<StatusCode, ApiError> {
    let name = dto.name.unwrap_or_else(|| dto.id.clone());
    app.create_tenant(&dto.id, &name)?;
    Ok(StatusCode::CREATED)
}

async fn tenants_delete(
    State(app): State<Arc<App>>,
    Path(id): Path<String>,
) -> Result<StatusCode, ApiError> {
    app.delete_tenant(&id)?;
    Ok(StatusCode::NO_CONTENT)
}

#[derive(serde::Serialize)]
struct ApiKeyDto {
    id: String,
    name: String,
    role: String,
    is_admin: bool,
    created_at: i64,
    revoked: bool,
}

/// List a tenant's API keys (metadata only — never the secret).
async fn tenant_keys_list(
    State(app): State<Arc<App>>,
    Path(id): Path<String>,
) -> Result<Json<Vec<ApiKeyDto>>, ApiError> {
    let keys = app
        .list_api_keys()?
        .into_iter()
        .filter(|k| k.tenant_id.as_deref() == Some(id.as_str()))
        .map(|k| ApiKeyDto {
            id: k.id,
            name: k.name,
            role: k.permissions,
            is_admin: k.is_admin,
            created_at: k.created_at,
            revoked: k.revoked,
        })
        .collect();
    Ok(Json(keys))
}

#[derive(serde::Deserialize)]
struct NewKeyDto {
    name: String,
    /// read | write | admin (default write).
    role: Option<String>,
}

/// Mint a key bound to this tenant; returns the plaintext **once**.
async fn tenant_keys_create(
    State(app): State<Arc<App>>,
    Path(id): Path<String>,
    Json(dto): Json<NewKeyDto>,
) -> Result<Json<serde_json::Value>, ApiError> {
    let role = dto.role.unwrap_or_else(|| "write".into());
    let key = app.create_api_key(&dto.name, &role, Some(&id), false)?;
    Ok(Json(serde_json::json!({ "key": key })))
}

async fn tenant_keys_revoke(
    State(app): State<Arc<App>>,
    Path((_id, kid)): Path<(String, String)>,
) -> Result<StatusCode, ApiError> {
    app.revoke_api_key(&kid)?;
    Ok(StatusCode::NO_CONTENT)
}

// ---- Admin cross-tenant data browse ([[WEIR-T-0094]]) — platform-admin (authz `Scope::Platform`);
// the tenant comes from the path, and each handler reuses the same tenant-scoped `App` method. ----

async fn t_connections(
    State(app): State<Arc<App>>,
    Path(tid): Path<String>,
) -> Result<Json<Vec<ConnectionDto>>, ApiError> {
    let mut dtos = Vec::new();
    for c in app.list_connections(&tid)? {
        let mut dto = ConnectionDto::from_connection(&c);
        if let Ok(st) = app.connection_state(&tid, &c.name) {
            dto.cursor = st.cursor;
            dto.chunks = st.chunks;
            dto.dead_lettered = st.dead_lettered;
        }
        dtos.push(dto);
    }
    Ok(Json(dtos))
}

async fn t_connection(
    State(app): State<Arc<App>>,
    Path((tid, name)): Path<(String, String)>,
) -> Result<Json<ConnectionDto>, ApiError> {
    Ok(Json(ConnectionDto::from_connection(
        &app.get_connection(&tid, &name)?,
    )))
}

async fn t_run(
    State(app): State<Arc<App>>,
    Path((tid, name)): Path<(String, String)>,
) -> Result<Json<RunDto>, ApiError> {
    let id = app.plan_run(&tid, &name)?;
    Ok(Json(RunDto {
        work_unit_id: id,
        state: "pending".to_string(),
    }))
}

/// Tenant-scoped start/stop of a resident connection ([[WEIR-I-0035]]) — mirrors the un-scoped
/// `start`/`stop`, but the tenant comes from the path (the UI scopes calls to `/tenants/{id}/…`,
/// so without these the button POSTs fell through to the SPA fallback and silently no-op'd).
async fn t_start(
    State(app): State<Arc<App>>,
    Path((tid, name)): Path<(String, String)>,
) -> Result<Json<serde_json::Value>, ApiError> {
    let id = app.start(&tid, &name)?;
    Ok(Json(serde_json::json!({
        "name": name, "started": id.is_some(), "work_unit_id": id,
    })))
}

async fn t_stop(
    State(app): State<Arc<App>>,
    Path((tid, name)): Path<(String, String)>,
) -> Result<Json<serde_json::Value>, ApiError> {
    let cancelled = app.stop(&tid, &name)?;
    Ok(Json(
        serde_json::json!({ "name": name, "cancelled": cancelled }),
    ))
}

async fn t_runs(
    State(app): State<Arc<App>>,
    Path((tid, name)): Path<(String, String)>,
) -> Result<Json<Vec<WorkUnitStatus>>, ApiError> {
    Ok(Json(app.history(&tid, &name)?))
}

async fn t_dead_letters(
    State(app): State<Arc<App>>,
    Path((tid, name)): Path<(String, String)>,
) -> Result<Json<Vec<DeadLetterRecord>>, ApiError> {
    Ok(Json(app.dead_letters(&tid, &name, 200)?))
}

async fn t_logs(
    State(app): State<Arc<App>>,
    Path((tid, name)): Path<(String, String)>,
) -> Result<Json<Vec<LogRecord>>, ApiError> {
    Ok(Json(app.logs(&tid, &name, 200)?))
}

async fn t_state(
    State(app): State<Arc<App>>,
    Path((tid, name)): Path<(String, String)>,
) -> Result<Json<ConnectionState>, ApiError> {
    Ok(Json(app.connection_state(&tid, &name)?))
}

async fn t_catalog(
    State(app): State<Arc<App>>,
    Path(tid): Path<String>,
) -> Result<Json<Vec<CatalogEntry>>, ApiError> {
    Ok(Json(app.list_connectors(&tid)?))
}

async fn t_recent(
    State(app): State<Arc<App>>,
    Path(tid): Path<String>,
) -> Result<Json<Vec<RunRow>>, ApiError> {
    Ok(Json(app.recent_runs(&tid, 50)?))
}

/// Maps an [`AppError`] to an HTTP response.
struct ApiError(StatusCode, String);

impl From<AppError> for ApiError {
    fn from(e: AppError) -> Self {
        let code = match e {
            AppError::NotFound(_) => StatusCode::NOT_FOUND,
            // Bad input (incl. an invalid manifest at onboard) → 4xx, not 5xx.
            AppError::Config(_) => StatusCode::BAD_REQUEST,
            _ => StatusCode::INTERNAL_SERVER_ERROR,
        };
        ApiError(code, e.to_string())
    }
}

impl IntoResponse for ApiError {
    fn into_response(self) -> Response {
        (self.0, Json(serde_json::json!({ "error": self.1 }))).into_response()
    }
}
