//! Generates the **self-contained** WASM-guest connector crate. Its v1 `read` is a
//! **typed server-streaming** method (`ReadContext` → `Stream<ReadMessage>`,
//! [[WEIR-A-0029]]) doing real brokered HTTP via `fidius_guest::http` (the host's
//! `EgressPolicy` authorizes it — the two-key gate with the package's `http`
//! capability). `config` is bound once at construction (configured instance).
//!
//! The interface types are defined **locally** (`WitType`) because `emit_wit`
//! parses only this crate's `src/lib.rs`; they mirror `weir-connector-types`'s WIT
//! so the load-time interface-hash matches the host. The `config` construct wire +
//! the raw `write` envelope use `weir-connector-types` (serde) directly.

use std::path::PathBuf;

use weir_manifest::{Manifest, Pagination, Stream};

use crate::{GeneratedCrate, page_size, pascal_case, rust_str, selector_expr, snake_case};

/// The one canonical guest-contract block ([[WEIR-I-0031]]), emitted verbatim as each guest's
/// `src/weir_guest_types.rs` (`emit_wit` follows `mod weir_guest_types;` into it). It mirrors
/// `weir-connector-types`; the drift-guard test keeps every guest byte-identical to this. Edit the
/// contract in `guest_contract.rs.in`, never inline.
pub(crate) const GUEST_CONTRACT: &str = include_str!("guest_contract.rs.in");

pub(crate) fn generate(m: &Manifest) -> GeneratedCrate {
    let crate_name = format!("weir-{}-wasm", snake_case(&m.spec.name).replace('_', "-"));
    GeneratedCrate {
        files: vec![
            (PathBuf::from("Cargo.toml"), cargo_toml(m, &crate_name)),
            (PathBuf::from("build.rs"), build_rs()),
            (PathBuf::from("src/lib.rs"), lib_rs(m)),
            // The contract block is its own module file, sourced from the one canonical copy.
            (
                PathBuf::from("src/weir_guest_types.rs"),
                GUEST_CONTRACT.to_string(),
            ),
        ],
    }
}

fn cargo_toml(m: &Manifest, crate_name: &str) -> String {
    format!(
        r#"# GENERATED by weir-codegen from manifest `{name}` — do not edit by hand.
# Standalone workspace: this guest is built on its own for wasm32-wasip2, not as
# a member of the weir workspace.
[workspace]

[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
fidius-guest = "0.5.3"
fidius-macro = "0.5.3"
wit-bindgen = "0.44"
# Fidius-free serde types + codec, shared with the host: the configured-construct
# Config wire + the raw `write` envelope. (The typed interface types are local.)
weir-connector-types = {{ path = "../../crates/weir-connector-types" }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"

[build-dependencies]
fidius-build = "0.5.3"

[profile.release]
opt-level = "s"
lto = true
strip = true
"#,
        name = m.spec.name,
        crate_name = crate_name,
    )
}

fn build_rs() -> String {
    "// GENERATED by weir-codegen — do not edit by hand.\nfn main() {\n    fidius_build::emit_wit();\n}\n"
        .to_string()
}

/// The self-contained guest: local `WitType` interface types (mirroring the
/// contract), a manifest-driven `discover`, and a typed streaming `read` that does
/// real `fidius_guest::http` GETs (paginated + cursor-tracked) and yields
/// `ReadMessage`s. `config` is bound at construction.
fn lib_rs(m: &Manifest) -> String {
    let ident = pascal_case(&m.spec.name);
    let mut streams = String::new();
    for s in &m.streams {
        let modes = if s.incremental.is_some() {
            "vec![SyncMode::FullRefresh, SyncMode::Incremental]"
        } else {
            "vec![SyncMode::FullRefresh]"
        };
        let default_cursor = match &s.incremental {
            Some(inc) => format!("Some({}.to_string())", rust_str(&inc.cursor_field)),
            None => "None".to_string(),
        };
        streams.push_str(&format!(
            "            StreamInfo {{ name: {}.to_string(), namespace: None, \
             schema: ArrowSchemaIpc {{ ipc: Vec::new() }}, supported_sync_modes: {modes}, \
             source_defined_cursor: {}, default_cursor_field: {default_cursor}, \
             source_defined_primary_key: None, partitioning: PartitionScheme::Unpartitioned }},\n",
            rust_str(&s.name),
            s.incremental.is_some(),
        ));
    }

    // read dispatch arms (one per stream): fetch → Records + Checkpoint, or Fatal.
    let mut read_dispatch = String::new();
    for s in &m.streams {
        read_dispatch.push_str(&format!(
            "            {} => match read_{}(&base_url, &ctx) {{\n                \
             Ok((rows, cursor)) => vec![ReadMessage::Records(RecordBatch::Rows(rows)), ReadMessage::Checkpoint(StreamState {{ cursor, opaque: Vec::new() }})],\n                \
             Err(e) => vec![ReadMessage::Fatal(e)],\n            }},\n",
            rust_str(&s.name),
            snake_case(&s.name)
        ));
    }

    // base_url_from + per-stream read fns (free fns appended after the impls).
    let mut read_fns = format!(
        "fn base_url_from(config: &weir_connector_types::Config) -> String {{\n    \
         serde_json::from_str::<serde_json::Value>(&config.json)\n        .ok()\n        \
         .and_then(|v| v.get(\"base_url\").and_then(|b| b.as_str()).map(str::to_string))\n        \
         .unwrap_or_else(|| {}.to_string())\n}}\n\n",
        rust_str(&m.base_url)
    );
    for s in &m.streams {
        read_fns.push_str(&read_fn(s));
    }

    format!(
        r##"// GENERATED by weir-codegen from manifest `{name}` — do not edit by hand.
//! Self-contained WASM guest for the `{name}` declarative source (v1 streaming).
#![allow(clippy::all)]

use fidius_macro::{{plugin_impl, plugin_interface, WitType}};
use weir_guest_types::*;

mod weir_guest_types;

#[plugin_interface(version = 1, buffer = PluginAllocated, crate = "fidius_guest")]
pub trait Connector: Send + Sync {{
    fn spec(&self) -> ConnectorSpec;
    fn check(&self, config: Config) -> CheckResult;
    #[optional(since = 1)]
    fn discover(&self, config: Config) -> DiscoverOutcome;
    #[optional(since = 1)]
    fn read(&self, ctx: ReadContext) -> fidius_guest::Stream<ReadMessage>;
    #[optional(since = 1)]
    fn write(&self, ctx: WriteContext, batches: fidius_guest::Stream<RecordBatch>) -> WriteOutcome;
}}

pub struct {ident} {{ cfg: weir_connector_types::Config }}

#[plugin_impl(Connector, crate = "fidius_guest", config = weir_connector_types::Config)]
impl Connector for {ident} {{
    fn spec(&self) -> ConnectorSpec {{
        ConnectorSpec {{
            name: {name_lit}.to_string(),
            connector_version: {version_lit}.to_string(),
            contract_version: 1,
            config_schema: {config_schema_lit}.to_string(),
            roles: vec![ConnectorRole::Source],
            supported_sync_modes: vec![SyncMode::FullRefresh, SyncMode::Incremental],
        }}
    }}

    fn check(&self, _config: Config) -> CheckResult {{
        CheckResult {{ success: true, message: None }}
    }}

    fn discover(&self, _config: Config) -> DiscoverOutcome {{
        DiscoverOutcome::Catalog(Catalog {{ streams: vec![
{streams}        ] }})
    }}

    fn read(&self, ctx: ReadContext) -> fidius_guest::Stream<ReadMessage> {{
        let base_url = base_url_from(&self.cfg);
        let msgs: Vec<ReadMessage> = match ctx.stream.stream.as_str() {{
{read_dispatch}            other => vec![ReadMessage::Fatal(ConnectorError::fatal(format!("unknown stream `{{other}}`")))],
        }};
        fidius_guest::Stream::from_iter(msgs)
    }}

    fn write(&self, _ctx: WriteContext, mut batches: fidius_guest::Stream<RecordBatch>) -> WriteOutcome {{
        while batches.next_item().is_some() {{}}
        WriteOutcome {{
            state: StreamState {{ cursor: None, opaque: Vec::new() }},
            diagnostics: Vec::new(),
            dead_letters: Vec::new(),
            result: WriteResult::Err(ConnectorError::fatal("{name} is a source, not a destination")),
        }}
    }}
}}

impl {ident} {{
    fn configure(cfg: weir_connector_types::Config) -> Self {{ Self {{ cfg }} }}
}}

{read_fns}"##,
        name = m.spec.name,
        name_lit = rust_str(&m.spec.name),
        version_lit = rust_str(&m.spec.version),
        config_schema_lit =
            rust_str(r#"{"type":"object","properties":{"base_url":{"type":"string"}}}"#),
        ident = ident,
        streams = streams,
        read_dispatch = read_dispatch,
        read_fns = read_fns,
    )
}

/// One `read_<stream>` helper: the paginated HTTP loop over `fidius_guest::http`
/// (brokered by the host EgressPolicy), with optional cursor tracking. Returns the
/// local `ConnectorError` so the impl can wrap it in `ReadMessage::Fatal`.
fn read_fn(s: &Stream) -> String {
    let fields = s
        .schema
        .iter()
        .map(|f| rust_str(&f.name))
        .collect::<Vec<_>>()
        .join(", ");
    let selector = selector_expr(s);
    let size = page_size(&s.pagination);

    let cursor_track = match &s.incremental {
        Some(inc) => format!(
            "                if let Some(cv) = rec.get({}) {{\n                    \
             let cs = cv.as_str().map(str::to_string).unwrap_or_else(|| cv.to_string());\n                    \
             if cursor.as_deref().map_or(true, |cur| cs.as_str() > cur) {{ cursor = Some(cs); }}\n                }}\n",
            rust_str(&inc.cursor_field)
        ),
        None => String::new(),
    };

    let cursor_param = match &s.incremental {
        Some(inc) => format!(
            "            if let Some(c) = &cursor {{ url.push_str(&format!(\"&{}={{}}\", c)); }}\n",
            inc.cursor_param
        ),
        None => String::new(),
    };

    let (pos_init, page_params, advance) = match &s.pagination {
        Some(Pagination::Page {
            page_param,
            size_param,
            ..
        }) => (
            "        let mut page: u64 = 1;\n",
            format!(
                "            url.push_str(&format!(\"?{}={{}}&{}={{}}\", page, {size}u64));\n",
                page_param, size_param
            ),
            "            page += 1;\n",
        ),
        Some(Pagination::Offset {
            offset_param,
            limit_param,
            ..
        }) => (
            "        let mut offset: u64 = 0;\n",
            format!(
                "            url.push_str(&format!(\"?{}={{}}&{}={{}}\", offset, {size}u64));\n",
                offset_param, limit_param
            ),
            "            offset += n as u64;\n",
        ),
        // Cursor pagination is a runtime-only feature; legacy codegen emits no paginator.
        Some(Pagination::Cursor { .. }) | Some(Pagination::LinkHeader) | None => {
            ("", String::new(), "")
        }
    };

    let record_loop = format!(
        "            for rec in &records {{\n                \
         let mut obj = serde_json::Map::new();\n                \
         for f in FIELDS {{ if let Some(v) = rec.get(*f) {{ obj.insert((*f).to_string(), v.clone()); }} }}\n{cursor_track}                \
         rows.push(serde_json::Value::Object(obj).to_string());\n            }}\n"
    );

    format!(
        "fn read_{name}(base_url: &str, ctx: &ReadContext) \
         -> Result<(Vec<String>, Option<String>), ConnectorError> {{\n    \
         const FIELDS: &[&str] = &[{fields}];\n    \
         let mut rows: Vec<String> = Vec::new();\n    \
         let mut cursor = ctx.state.cursor.clone();\n{pos_init}    loop {{\n        \
         let mut url = format!(\"{{}}{{}}\", base_url, {path});\n{page_params}{cursor_param}        \
         let body = match fidius_guest::http::get(&url) {{\n            \
         Ok(r) => r.text(),\n            \
         Err(e) => return Err(ConnectorError::transient(format!(\"request to {{url}} failed: {{e}}\"))),\n        }};\n        \
         let val: serde_json::Value = match serde_json::from_str(&body) {{ Ok(v) => v, Err(e) => return Err(ConnectorError::fatal(format!(\"invalid JSON response: {{e}}\"))) }};\n        \
         let records = match {selector} {{ Some(a) => a, None => return Err(ConnectorError::fatal(\"record selector did not match a JSON array\")) }};\n        \
         if records.is_empty() {{ break; }}\n        let n = records.len();\n{record_loop}        \
         if n < {size}usize {{ break; }}\n{advance}    }}\n    Ok((rows, cursor))\n}}\n\n",
        name = snake_case(&s.name),
        path = rust_str(&s.path),
    )
}
