apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weir-server.fullname" . }}
  labels:
    {{- include "weir-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  WEIR_DB: {{ .Values.store.url | quote }}
  {{- if .Values.oidc.enabled }}
  WEIR_OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | quote }}
  {{- end }}
