// GENERATED by weir-codegen from manifest `rest` — do not edit by hand.
//! Self-contained WASM guest for the `rest` declarative source (v1 streaming).
#![allow(clippy::all)]

use fidius_macro::{plugin_impl, plugin_interface, WitType};
use weir_guest_types::*;

mod weir_guest_types;

#[plugin_interface(version = 1, buffer = PluginAllocated, crate = "fidius_guest")]
pub trait Connector: Send + Sync {
    fn spec(&self) -> ConnectorSpec;
    fn check(&self, config: Config) -> CheckResult;
    #[optional(since = 1)]
    fn discover(&self, config: Config) -> DiscoverOutcome;
    #[optional(since = 1)]
    fn read(&self, ctx: ReadContext) -> fidius_guest::Stream<ReadMessage>;
    #[optional(since = 1)]
    fn write(&self, ctx: WriteContext, batches: fidius_guest::Stream<RecordBatch>) -> WriteOutcome;
}

pub struct Rest { cfg: weir_connector_types::Config }

#[plugin_impl(Connector, crate = "fidius_guest", config = weir_connector_types::Config)]
impl Connector for Rest {
    fn spec(&self) -> ConnectorSpec {
        ConnectorSpec {
            name: "rest".to_string(),
            connector_version: "0.1.0".to_string(),
            contract_version: 1,
            config_schema: "{\"type\":\"object\",\"required\":[\"base_url\",\"path\"],\"properties\":{\
                \"base_url\":{\"type\":\"string\",\"title\":\"Base URL\"},\
                \"path\":{\"type\":\"string\",\"title\":\"Path\"},\
                \"record_path\":{\"type\":\"string\",\"title\":\"Record path (dot-sep; blank = top-level array)\"},\
                \"page_param\":{\"type\":\"string\",\"title\":\"Page query param (blank = no pagination)\"},\
                \"offset_param\":{\"type\":\"string\",\"title\":\"Offset query param (offset pagination)\"},\
                \"page_cursor_path\":{\"type\":\"string\",\"title\":\"Next-cursor response path (dot-sep; cursor pagination)\"},\
                \"page_cursor_param\":{\"type\":\"string\",\"title\":\"Cursor query param\"},\
                \"page_size_param\":{\"type\":\"string\",\"title\":\"Page-size query param\"},\
                \"page_size\":{\"type\":\"integer\",\"title\":\"Page size\"},\
                \"cursor_field\":{\"type\":\"string\",\"title\":\"Cursor field (blank = full refresh)\"},\
                \"cursor_param\":{\"type\":\"string\",\"title\":\"Cursor query param\"}}}".to_string(),
                // Auth is resolved + injected host-side by the egress policy
                // ([[WEIR-A-0033]]); the guest declares no auth config and never sees a
                // credential.
            roles: vec![ConnectorRole::Source],
            supported_sync_modes: vec![SyncMode::FullRefresh, SyncMode::Incremental],
        }
    }

    fn check(&self, _config: Config) -> CheckResult {
        CheckResult { success: true, message: None }
    }

    fn discover(&self, _config: Config) -> DiscoverOutcome {
        // Generic source: the stream is defined by config (path + record_path), so
        // discover advertises one configurable "records" stream.
        DiscoverOutcome::Catalog(Catalog { streams: vec![
            StreamInfo { name: "records".to_string(), namespace: None, schema: ArrowSchemaIpc { ipc: Vec::new() }, supported_sync_modes: vec![SyncMode::FullRefresh, SyncMode::Incremental], source_defined_cursor: false, default_cursor_field: None, source_defined_primary_key: None, partitioning: PartitionScheme::Unpartitioned },
        ] })
    }

    fn read(&self, ctx: ReadContext) -> fidius_guest::Stream<ReadMessage> {
        let msgs: Vec<ReadMessage> = match fetch_records(&self.cfg, &ctx) {
            Ok((rows, cursor)) => vec![
                ReadMessage::Records(RecordBatch::Rows(rows)),
                ReadMessage::Checkpoint(StreamState { cursor, opaque: Vec::new() }),
            ],
            Err(e) => vec![ReadMessage::Fatal(e)],
        };
        fidius_guest::Stream::from_iter(msgs)
    }

    fn write(&self, _ctx: WriteContext, mut batches: fidius_guest::Stream<RecordBatch>) -> WriteOutcome {
        while batches.next_item().is_some() {}
        WriteOutcome {
            state: StreamState { cursor: None, opaque: Vec::new() },
            diagnostics: Vec::new(),
            dead_letters: Vec::new(),
            result: WriteResult::Err(ConnectorError::fatal("rest is a source, not a destination")),
        }
    }
}

impl Rest {
    fn configure(cfg: weir_connector_types::Config) -> Self { Self { cfg } }
}

/// Parsed config for the generic REST source. Mirrors the declarative manifest
/// (url_base + path + record selector + pagination + datetime cursor), so a
/// vendored manifest's stream maps straight onto a connection config.
struct RestCfg {
    base_url: String,
    path: String,
    /// Dpath to the records array (`["data","items"]`); empty = top-level array.
    record_path: Vec<String>,
    /// Query param for the page number (None = single request, no pagination).
    page_param: Option<String>,
    /// Query param for a row offset (`?offset=N`); advances by `page_size` each page.
    /// Mutually exclusive with `page_param` in practice.
    offset_param: Option<String>,
    page_size_param: Option<String>,
    page_size: Option<u64>,
    /// Opaque cursor pagination: dpath to the next-page token in the response (empty = none)
    /// + the query param to send it as. Stop when the token is absent/empty.
    page_cursor_path: Vec<String>,
    page_cursor_param: Option<String>,
    /// Link-header pagination ([[WEIR-T-0070]]): follow `Link: <url>; rel="next"` from the
    /// response headers (GitHub-style) until absent. The next URL is absolute.
    page_link_header: bool,
    /// Record field whose max advances the incremental cursor (None = full refresh).
    cursor_field: Option<String>,
    cursor_param: Option<String>,
    /// Richer datetime cursor ([[WEIR-T-0070]]): initial lower bound (`cursor_start`, used
    /// only on the first run when there's no state) + an upper bound
    /// (`cursor_end_param`=`cursor_end`, sent on every request).
    cursor_start: Option<String>,
    cursor_end_param: Option<String>,
    cursor_end: Option<String>,
    /// Max retries on a transient failure (429 / 5xx / transport) with exponential backoff
    /// ([[WEIR-T-0069]]); honors `Retry-After`. Default 4.
    max_retries: u32,
    /// Request options ([[WEIR-T-0068]]): HTTP method (`GET` default | `POST`), a POST body
    /// (config-templated), and static request headers (e.g. `Notion-Version`). Auth headers
    /// are still host-injected ([[WEIR-A-0033]]).
    http_method: String,
    request_body: Option<String>,
    request_headers: Vec<(String, String)>,
    /// Partition router ([[WEIR-T-0064]]): `list` (one request per `partition_values`) or
    /// `substream` (read `parent_path`, one request per `parent_key` of each parent
    /// record). The slice value is templated into the path as `{{ stream_partition.* }}`.
    partition_kind: Option<String>,
    partition_values: Vec<String>,
    parent_path: Option<String>,
    parent_record_path: Vec<String>,
    parent_key: Option<String>,
}

fn parse_cfg(config: &weir_connector_types::Config) -> RestCfg {
    let v: serde_json::Value =
        serde_json::from_str(&config.json).unwrap_or(serde_json::Value::Null);
    let s = |k: &str| {
        v.get(k)
            .and_then(|x| x.as_str())
            .map(str::to_string)
            .filter(|x| !x.is_empty())
    };
    RestCfg {
        // base_url + path may be templated (`{{ config['subdomain'] }}`) — render against
        // the same config so per-connection tenant/account values land in the URL.
        base_url: render_template(&s("base_url").unwrap_or_default(), &v),
        path: render_template(&s("path").unwrap_or_default(), &v),
        record_path: s("record_path")
            .map(|p| p.split('.').map(str::to_string).collect())
            .unwrap_or_default(),
        page_param: s("page_param"),
        offset_param: s("offset_param"),
        page_size_param: s("page_size_param"),
        page_size: v.get("page_size").and_then(|x| x.as_u64()),
        page_cursor_path: s("page_cursor_path")
            .map(|p| p.split('.').map(str::to_string).collect())
            .unwrap_or_default(),
        page_cursor_param: s("page_cursor_param"),
        page_link_header: v.get("page_link_header").and_then(|x| x.as_bool()).unwrap_or(false),
        cursor_field: s("cursor_field"),
        cursor_param: s("cursor_param"),
        // start/end may be `{{ config['…'] }}` — render against the connection config.
        cursor_start: s("cursor_start").map(|t| render_template(&t, &v)),
        cursor_end_param: s("cursor_end_param"),
        cursor_end: s("cursor_end").map(|t| render_template(&t, &v)),
        max_retries: v.get("max_retries").and_then(|x| x.as_u64()).unwrap_or(4) as u32,
        http_method: s("http_method").unwrap_or_else(|| "GET".to_string()),
        request_body: s("request_body").map(|t| render_template(&t, &v)),
        request_headers: v
            .get("request_headers")
            .and_then(|x| x.as_object())
            .map(|o| {
                o.iter()
                    .filter_map(|(k, val)| val.as_str().map(|s| (k.clone(), s.to_string())))
                    .collect()
            })
            .unwrap_or_default(),
        partition_kind: s("partition_kind"),
        partition_values: v
            .get("partition_values")
            .and_then(|x| x.as_array())
            .map(|a| a.iter().filter_map(|x| x.as_str().map(str::to_string)).collect())
            .unwrap_or_default(),
        parent_path: s("parent_path"),
        parent_record_path: s("parent_record_path")
            .map(|p| p.split('.').map(str::to_string).collect())
            .unwrap_or_default(),
        parent_key: s("parent_key"),
    }
}

/// Extract `KEY` from a `{{ }}` expr of the form `config['KEY']` / `config["KEY"]` /
/// `config.KEY` (whitespace-tolerant). Returns None for anything else.
fn config_key(expr: &str) -> Option<String> {
    let e = expr.trim().strip_prefix("config")?.trim();
    if let Some(rest) = e.strip_prefix('[') {
        let rest = rest.trim().trim_start_matches(['\'', '"']);
        return rest.split(['\'', '"', ']']).next().map(|k| k.trim().to_string());
    }
    e.strip_prefix('.').map(|rest| rest.trim().to_string())
}

/// Substitute `{{ config['KEY'] }}` placeholders in `t` with the matching string value
/// from the connection config `v`. Used for templated `url_base`/`path` (tenant
/// subdomain, account id, …). An unknown *config* key renders empty. Non-config `{{ … }}`
/// exprs (e.g. `{{ stream_partition.* }}`) are **left intact** for a later pass.
fn render_template(t: &str, v: &serde_json::Value) -> String {
    let mut out = t.to_string();
    let mut from = 0;
    while let Some(rel_start) = out[from..].find("{{") {
        let start = from + rel_start;
        let Some(rel_end) = out[start..].find("}}") else { break };
        let end = start + rel_end + 2;
        let inner = &out[start + 2..end - 2];
        match config_key(inner) {
            Some(key) => {
                let val = v.get(&key).and_then(|x| x.as_str()).unwrap_or("").to_string();
                out.replace_range(start..end, &val);
                from = start + val.len();
            }
            None => from = end, // leave non-config templates intact
        }
    }
    out
}

/// Substitute `{{ stream_partition.* }}` placeholders in `path` with this slice's `value`
/// ([[WEIR-T-0064]]). There is one partition value per slice, so the exact field inside
/// the braces doesn't need matching.
fn render_partition(path: &str, value: &str) -> String {
    let mut out = path.to_string();
    let mut from = 0;
    while let Some(rel_start) = out[from..].find("{{") {
        let start = from + rel_start;
        let Some(rel_end) = out[start..].find("}}") else { break };
        let end = start + rel_end + 2;
        if out[start + 2..end - 2].trim().starts_with("stream_partition") {
            out.replace_range(start..end, value);
            from = start + value.len();
        } else {
            from = end;
        }
    }
    out
}

/// Descend `path` into `v` (dpath); empty path returns `v` itself.
fn navigate<'a>(v: &'a serde_json::Value, path: &[String]) -> Option<&'a serde_json::Value> {
    let mut cur = v;
    for seg in path {
        cur = cur.get(seg)?;
    }
    Some(cur)
}

/// Exponential backoff for retry `attempt` (0-based): 200ms, 400, 800, … capped at 8s.
fn backoff_ms(attempt: u32) -> u64 {
    (200u64 << attempt.min(5)).min(8000)
}

/// Parse a `Retry-After` header (integer seconds) → milliseconds, if present.
fn retry_after_ms(headers: &[(String, String)]) -> Option<u64> {
    headers
        .iter()
        .find(|(k, _)| k.eq_ignore_ascii_case("retry-after"))
        .and_then(|(_, v)| v.trim().parse::<u64>().ok())
        .map(|secs| secs * 1000)
}

/// Send `url` per the config's method/body/headers ([[WEIR-T-0068]]), retrying transient
/// failures (429 / 5xx / transport error) up to `max_retries` with exponential backoff,
/// honoring `Retry-After` ([[WEIR-T-0069]]). A non-retryable status is returned as `Ok` for
/// the caller to handle; a persistent transient one errors. Auth is injected host-side
/// ([[WEIR-A-0033]]); static `request_headers` (e.g. `Notion-Version`) are set by the guest.
fn send_with_retry(c: &RestCfg, url: &str) -> Result<fidius_guest::http::Response, ConnectorError> {
    let mut attempt: u32 = 0;
    loop {
        let mut req = if c.http_method.eq_ignore_ascii_case("POST") {
            let body = c.request_body.clone().unwrap_or_default().into_bytes();
            fidius_guest::http::Request::post(url, body)
        } else {
            fidius_guest::http::Request::get(url)
        };
        // Default User-Agent — some APIs (notably GitHub) reject requests without one
        // with a non-JSON error body. A manifest `request_headers` entry overrides it.
        let has_ua = c
            .request_headers
            .iter()
            .any(|(k, _)| k.eq_ignore_ascii_case("user-agent"));
        if !has_ua {
            req = req.header("user-agent", concat!("weir-rest/", env!("CARGO_PKG_VERSION")));
        }
        for (k, v) in &c.request_headers {
            req = req.header(k.as_str(), v.as_str());
        }
        match fidius_guest::http::send(req) {
            Ok(r) => {
                let retryable = r.status == 429 || (500..=599).contains(&r.status);
                if !retryable {
                    return Ok(r);
                }
                if attempt >= c.max_retries {
                    return Err(ConnectorError::transient(format!(
                        "request to {url} failed after {} retries (HTTP {})",
                        c.max_retries, r.status
                    )));
                }
                let wait = retry_after_ms(&r.headers).unwrap_or_else(|| backoff_ms(attempt));
                std::thread::sleep(std::time::Duration::from_millis(wait));
                attempt += 1;
            }
            Err(e) => {
                if attempt >= c.max_retries {
                    return Err(ConnectorError::transient(format!(
                        "request to {url} failed: {e}"
                    )));
                }
                std::thread::sleep(std::time::Duration::from_millis(backoff_ms(attempt)));
                attempt += 1;
            }
        }
    }
}

/// Parse an RFC 5988 `Link` header for the `rel="next"` URL, if present. e.g.
/// `Link: <https://api…?page=2>; rel="next", <…>; rel="last"` → the page-2 URL.
fn next_link_url(headers: &[(String, String)]) -> Option<String> {
    let link = headers
        .iter()
        .find(|(k, _)| k.eq_ignore_ascii_case("link"))
        .map(|(_, v)| v.as_str())?;
    for part in link.split(',') {
        // A segment like `<url>; rel="next"`.
        let is_next = part
            .split(';')
            .skip(1)
            .any(|p| p.trim().trim_start_matches("rel=").trim_matches(['"', ' ']) == "next");
        if is_next {
            let start = part.find('<')?;
            let end = part[start..].find('>')? + start;
            return Some(part[start + 1..end].trim().to_string());
        }
    }
    None
}

/// Route a read through the partition router (if any), then concatenate the records of
/// every slice ([[WEIR-T-0064]]): `list` runs one fetch per static value; `substream`
/// reads the parent stream and runs one fetch per parent `parent_key`; the slice value is
/// templated into the child path as `{{ stream_partition.* }}`. No router → one flat fetch.
fn fetch_records(
    config: &weir_connector_types::Config,
    ctx: &ReadContext,
) -> Result<(Vec<String>, Option<String>), ConnectorError> {
    let c = parse_cfg(config);
    match c.partition_kind.as_deref() {
        Some("list") => {
            let mut rows = Vec::new();
            let mut cursor = ctx.state.cursor.clone();
            for val in &c.partition_values {
                let path = render_partition(&c.path, val);
                let (r, cur) = fetch_slice(&c, &path, &c.record_path, &cursor)?;
                rows.extend(r);
                cursor = cur; // the cursor only advances, so the last slice wins
            }
            Ok((rows, cursor))
        }
        Some("substream") => {
            let parent_path = c.parent_path.clone().unwrap_or_default();
            let (parents, _) = fetch_slice(&c, &parent_path, &c.parent_record_path, &None)?;
            let key = c.parent_key.clone().unwrap_or_else(|| "id".to_string());
            let mut rows = Vec::new();
            let mut cursor = ctx.state.cursor.clone();
            for prow in &parents {
                let pv: serde_json::Value = match serde_json::from_str(prow) {
                    Ok(v) => v,
                    Err(_) => continue,
                };
                let id = match pv.get(&key) {
                    Some(serde_json::Value::String(s)) => s.clone(),
                    Some(other) => other.to_string(),
                    None => continue,
                };
                let path = render_partition(&c.path, &id);
                let (r, cur) = fetch_slice(&c, &path, &c.record_path, &cursor)?;
                rows.extend(r);
                cursor = cur;
            }
            Ok((rows, cursor))
        }
        _ => fetch_slice(&c, &c.path, &c.record_path, &ctx.state.cursor),
    }
}

/// Fetch one slice: GET `base_url+path` (with optional page/cursor query params), extract
/// the records array at `record_path`, emit each record **whole** (the engine's mapping
/// stage shapes them), paginating while a pagination param is set. Returns the rows + the
/// advanced incremental cursor.
fn fetch_slice(
    c: &RestCfg,
    path: &str,
    record_path: &[String],
    cursor_in: &Option<String>,
) -> Result<(Vec<String>, Option<String>), ConnectorError> {
    let mut rows: Vec<String> = Vec::new();
    // First run (no state) starts from the configured lower bound, if any.
    let mut cursor = cursor_in.clone().or_else(|| c.cursor_start.clone());
    let mut page: u64 = 1;
    let mut offset: u64 = 0;
    let mut page_cursor: Option<String> = None;
    let mut link_next: Option<String> = None;
    const MAX_PAGES: u64 = 1000;
    loop {
        // A Link-header page carries an absolute next URL; otherwise build base_url+path+query.
        let url = if let Some(u) = link_next.take() {
            u
        } else {
            let mut url = format!("{}{}", c.base_url, path);
            let mut q: Vec<String> = Vec::new();
            if let Some(p) = &c.page_param {
                q.push(format!("{p}={page}"));
            }
            if let Some(p) = &c.offset_param {
                q.push(format!("{p}={offset}"));
            }
            if let (Some(p), Some(tok)) = (&c.page_cursor_param, &page_cursor) {
                q.push(format!("{p}={tok}"));
            }
            if let (Some(p), Some(sz)) = (&c.page_size_param, c.page_size) {
                q.push(format!("{p}={sz}"));
            }
            if let (Some(p), Some(cur)) = (&c.cursor_param, &cursor) {
                q.push(format!("{p}={cur}"));
            }
            if let (Some(p), Some(e)) = (&c.cursor_end_param, &c.cursor_end) {
                q.push(format!("{p}={e}"));
            }
            if !q.is_empty() {
                url.push('?');
                url.push_str(&q.join("&"));
            }
            url
        };

        // Auth is injected host-side by the egress policy ([[WEIR-A-0033]]); the guest
        // sends a plain request. Transient failures (429 / 5xx / transport) retry with
        // exponential backoff, honoring `Retry-After` ([[WEIR-T-0069]]).
        let resp = send_with_retry(c, &url)?;
        let body = resp.text();
        // Past page 1, a non-JSON body is end-of-data: paginated APIs often answer one
        // page beyond the last with a 404 whose body is an HTML/empty error page.
        let val: serde_json::Value = match serde_json::from_str(&body) {
            Ok(v) => v,
            Err(_) if page > 1 => break,
            Err(e) => return Err(ConnectorError::fatal(format!("invalid JSON response: {e}"))),
        };
        // Past page 1, a missing record_path / non-array body is end-of-data: many
        // paginated APIs return a 404 error object (e.g. `{"error": "..."}`) one page
        // beyond the last instead of an empty array. On page 1 it's a real config error.
        let node = match navigate(&val, record_path) {
            Some(n) => n,
            None if page > 1 => break,
            None => {
                return Err(ConnectorError::fatal(format!(
                    "record_path {record_path:?} not found in response"
                )))
            }
        };
        let records: Vec<&serde_json::Value> = match node {
            serde_json::Value::Array(a) => a.iter().collect(),
            // A single-object resource (e.g. xkcd `/info.0.json`) — emit it as one record.
            serde_json::Value::Object(_) if page == 1 => vec![node],
            // Past page 1, a non-array body is end-of-data (a terminal error/empty page).
            _ if page > 1 => break,
            _ => {
                return Err(ConnectorError::fatal(
                    "record_path did not resolve to a JSON array or object",
                ))
            }
        };
        if records.is_empty() {
            break;
        }
        let n = records.len() as u64;
        for rec in records {
            if let Some(cf) = &c.cursor_field {
                if let Some(cv) = rec.get(cf) {
                    let cs = cv.as_str().map(str::to_string).unwrap_or_else(|| cv.to_string());
                    if cursor.as_deref().map_or(true, |cur| cs.as_str() > cur) {
                        cursor = Some(cs);
                    }
                }
            }
            rows.push(rec.to_string());
        }
        // Link-header pagination ([[WEIR-T-0070]]): follow `Link: <url>; rel="next"` from the
        // response headers until it's absent (GitHub-style). The next URL is absolute.
        if c.page_link_header {
            match next_link_url(&resp.headers) {
                Some(u) => {
                    link_next = Some(u);
                    page += 1;
                    if page > MAX_PAGES {
                        break;
                    }
                    continue;
                }
                None => break,
            }
        }
        // Advance: opaque cursor (`?cursor=<token>` from the response), page-increment
        // (`?page=N`), or offset (`?offset=N`, by page_size).
        let cursor_paginating = !c.page_cursor_path.is_empty();
        if c.page_param.is_none() && c.offset_param.is_none() && !cursor_paginating {
            break; // no pagination → single request
        }
        if cursor_paginating {
            // Read the next-page token from the response; absent/empty → last page.
            match navigate(&val, &c.page_cursor_path)
                .and_then(|x| x.as_str())
                .filter(|s| !s.is_empty())
            {
                Some(tok) => page_cursor = Some(tok.to_string()),
                None => break,
            }
        } else if let Some(sz) = c.page_size {
            if n < sz {
                break; // short page → last page
            }
        }
        page += 1;
        offset += c.page_size.unwrap_or(n);
        if page > MAX_PAGES {
            break;
        }
    }
    Ok((rows, cursor))
}
