author_email = "contact@colliery.io"
author_name = "Dylan Storey"
github_org = "colliery-io"
include_python_bindings = "true"
include_ui = "false"
initial_version = "0.0.1"
license = "Apache-2.0"
project_description = "An early-stage Rust project."
project_name = "weir"
project_slug = "weir"
rust_version = "1.93"
