"""Author WASM connectors.

`angreal connectors new <name>` — stamp a fresh connector crate under
`crates/connectors/<name>` from the canonical template (the `rest` connector's shared
WIT-type block + trait), leaving you a stub `impl Connector` to fill in. See
`docs/guides/connector-authoring.md`. ([[WEIR-T-0109]])
"""

import os
import shutil

import angreal

root = os.path.join(angreal.get_root(), "..")

connectors = angreal.command_group(name="connectors", about="author WASM connectors")


def _pascal(name):
    return "".join(part.capitalize() for part in name.replace("_", "-").split("-") if part)


# Every guest (full-code connector + test fixture) carries the WIT contract as a
# `src/weir_guest_types.rs` module, generated from the one canonical block ([[WEIR-I-0031]]).
# Guests are DISCOVERED by glob ([[WEIR-T-0172]]) — a new guest crate is covered the moment
# it exists; the old hand-list silently skipped mssql/snowflake/resident.
CANONICAL = os.path.join(root, "crates", "weir-codegen", "src", "guest_contract.rs.in")


def _guest_dirs():
    """Every guest crate dir under the two guest roots (has Cargo.toml + src/)."""
    dirs = []
    for parent in (
        os.path.join(root, "crates", "connectors"),
        os.path.join(root, "wasm-fixtures"),
    ):
        for name in sorted(os.listdir(parent)):
            d = os.path.join(parent, name)
            if (
                os.path.isdir(d)
                and os.path.isfile(os.path.join(d, "Cargo.toml"))
                and os.path.isdir(os.path.join(d, "src"))
            ):
                dirs.append(d)
    return dirs


GUESTS = _guest_dirs()


def _sync_guest(guest_dir, canonical):
    """Write `<guest>/src/weir_guest_types.rs` = canonical, and collapse any inline
    `mod weir_guest_types { … }` in lib.rs to `mod weir_guest_types;`. Idempotent."""
    with open(os.path.join(guest_dir, "src", "weir_guest_types.rs"), "w") as f:
        f.write(canonical)
    lib_path = os.path.join(guest_dir, "src", "lib.rs")
    with open(lib_path) as f:
        lines = f.readlines()
    out, i = [], 0
    while i < len(lines):
        if lines[i].startswith("mod weir_guest_types {"):
            out.append("mod weir_guest_types;\n")
            i += 1
            # The module's items are indented; its closing brace is the next col-0 `}`.
            while i < len(lines) and lines[i].rstrip() != "}":
                i += 1
            i += 1  # skip the closing brace
        else:
            out.append(lines[i])
            i += 1
    with open(lib_path, "w") as f:
        f.write("".join(out))


@connectors()
@angreal.command(
    name="new",
    about="scaffold a new WASM connector crate from the template",
)
@angreal.argument(
    name="name",
    help="connector name in kebab-case, e.g. 'my-api' (dir + crate name)",
    required=True,
)
def new(name):
    conns = os.path.join(root, "crates", "connectors")
    template = os.path.join(conns, "rest")
    dest = os.path.join(conns, name)
    if os.path.exists(dest):
        print(f"crates/connectors/{name} already exists — pick another name")
        return 1
    os.makedirs(os.path.join(dest, "src"), exist_ok=True)

    # Shared, unchanged scaffolding.
    shutil.copytree(os.path.join(template, "wit"), os.path.join(dest, "wit"))
    shutil.copy(os.path.join(template, "build.rs"), os.path.join(dest, "build.rs"))

    # Cargo.toml — the template's, renamed.
    with open(os.path.join(template, "Cargo.toml")) as f:
        cargo = f.read()
    cargo = cargo.replace("weir-rest-wasm", f"weir-{name}-wasm").replace(
        "weir REST/HTTP source connector (WASM component):"
        " config-driven declarative ingestion — base URL + path + record selector,"
        " pagination, and datetime-cursor incremental.",
        f"weir {name} connector (WASM component).",
    )
    with open(os.path.join(dest, "Cargo.toml"), "w") as f:
        f.write(cargo)

    # The WIT contract rides as a `weir_guest_types.rs` module from the canonical ([[WEIR-I-0031]]).
    with open(CANONICAL) as f:
        canonical = f.read()
    with open(os.path.join(dest, "src", "weir_guest_types.rs"), "w") as f:
        f.write(canonical)

    # lib.rs — the shared boilerplate (through the `Connector` trait) + a stub impl.
    with open(os.path.join(template, "src", "lib.rs")) as f:
        lines = f.readlines()
    # Keep everything up to and including the `Connector` trait's closing brace.
    tstart = next(i for i, ln in enumerate(lines) if ln.startswith("pub trait Connector"))
    end = next(i for i in range(tstart, len(lines)) if lines[i].rstrip() == "}")
    shared = "".join(lines[: end + 1])
    # Replace the generated banner with a connector-specific doc comment.
    shared = shared.replace(
        "// GENERATED by weir-codegen from manifest `rest` — do not edit by hand.\n"
        "//! Self-contained WASM guest for the `rest` declarative source (v1 streaming).\n",
        f"//! WASM guest for the `{name}` connector. Fill in the `impl Connector` below;\n"
        f"//! see docs/guides/connector-authoring.md. Requests are unsigned in the guest —\n"
        f"//! the host injects/signs credentials ([[WEIR-A-0033]]).\n",
    )
    ty = _pascal(name)
    stub = f'''

pub struct {ty} {{
    #[allow(dead_code)]
    cfg: weir_connector_types::Config,
}}

#[plugin_impl(Connector, crate = "fidius_guest", config = weir_connector_types::Config)]
impl Connector for {ty} {{
    fn spec(&self) -> ConnectorSpec {{
        ConnectorSpec {{
            name: "{name}".to_string(),
            connector_version: "0.1.0".to_string(),
            contract_version: 1,
            config_schema: "{{\\"type\\":\\"object\\",\\"properties\\":{{}}}}".to_string(),
            roles: vec![ConnectorRole::Source],
            supported_sync_modes: vec![SyncMode::FullRefresh],
        }}
    }}

    fn check(&self, _config: Config) -> CheckResult {{
        CheckResult {{ success: true, message: None }}
    }}

    fn discover(&self, _config: Config) -> DiscoverOutcome {{
        DiscoverOutcome::Catalog(Catalog {{ streams: vec![StreamInfo {{
            name: "records".to_string(),
            namespace: None,
            schema: ArrowSchemaIpc {{ ipc: Vec::new() }},
            supported_sync_modes: vec![SyncMode::FullRefresh],
            source_defined_cursor: false,
            default_cursor_field: None,
            source_defined_primary_key: None,
            partitioning: PartitionScheme::Unpartitioned,
        }}] }})
    }}

    fn read(&self, _ctx: ReadContext) -> fidius_guest::Stream<ReadMessage> {{
        // TODO: fetch records and emit Records(..) + Checkpoint(..).
        fidius_guest::Stream::from_iter(vec![
            ReadMessage::Records(RecordBatch::Rows(Vec::new())),
            ReadMessage::Checkpoint(StreamState {{ cursor: None, opaque: Vec::new() }}),
        ])
    }}

    fn write(&self, _ctx: WriteContext, mut batches: fidius_guest::Stream<RecordBatch>) -> WriteOutcome {{
        while batches.next_item().is_some() {{}}
        WriteOutcome {{
            state: StreamState {{ cursor: None, opaque: Vec::new() }},
            diagnostics: Vec::new(),
            dead_letters: Vec::new(),
            result: WriteResult::Err(ConnectorError::fatal("{name} is a source, not a destination")),
        }}
    }}
}}

impl {ty} {{
    fn configure(cfg: weir_connector_types::Config) -> Self {{
        Self {{ cfg }}
    }}
}}
'''
    with open(os.path.join(dest, "src", "lib.rs"), "w") as f:
        f.write(shared + stub)

    with open(os.path.join(dest, "README.md"), "w") as f:
        f.write(
            f"# weir `{name}` connector\n\n"
            "Scaffolded by `angreal connectors new`. See docs/guides/connector-authoring.md.\n\n"
            "- **Roles**: Source (edit `spec`).\n"
            "- **Auth**: resolved host-side ([[WEIR-A-0033]]); no secrets in the guest.\n"
        )

    print(f"scaffolded crates/connectors/{name} — fill in `impl Connector for {ty}` in src/lib.rs")
    print("build: (cd crates/connectors/%s && cargo build --release --target wasm32-wasip2)" % name)
    return 0


@connectors()
@angreal.command(
    name="sync-contract",
    about="regenerate every guest's weir_guest_types.rs from the one canonical block",
)
def sync_contract():
    """Write the canonical WIT contract ([[WEIR-I-0031]]) into every guest's
    `src/weir_guest_types.rs` and collapse any inline block to `mod weir_guest_types;`.
    Idempotent; run after editing `crates/weir-codegen/src/guest_contract.rs.in`. The
    `contract_drift` test asserts every checked-in copy matches the canonical."""
    with open(CANONICAL) as f:
        canonical = f.read()
    for guest in GUESTS:
        _sync_guest(guest, canonical)
        print(f"synced {os.path.relpath(guest, root)}/src/weir_guest_types.rs")
    print(f"{len(GUESTS)} guests synced to the canonical contract")
    return 0
